apiVersion: v1
kind: Service
metadata:
  name: node-hello-service
spec:
  type: NodePort
  selector:
    app: node-hello
  ports:
    - port: 3001         # Service port
      targetPort: 3001   # Container port
      nodePort: 30007    # Node port (external)
      
